import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dalvan
 */
public class CadastroFamilia extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFamilia
     */
    public CadastroFamilia() {
        initComponents();
        setSize(550,750);

    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomePrincipal = new javax.swing.JTextField();
        cpfPrincipal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        doenca = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Cadastro de família");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 100, 173, 25);

        jLabel1.setText("Integrante Principal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 160, 130, 14);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 420, 80, 14);

        nome.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(190, 420, 260, 19);

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 460, 60, 14);

        cpf.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(cpf);
        cpf.setBounds(190, 460, 150, 19);

        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 270, 70, 14);

        cep.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(cep);
        cep.setBounds(190, 290, 140, 19);

        jLabel6.setText("CEP:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 290, 60, 14);

        jLabel7.setText("Cidade:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 320, 70, 14);

        cidade.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cidade);
        cidade.setBounds(190, 320, 140, 19);

        jLabel8.setText("Estado:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 320, 50, 14);

        jLabel9.setText("Integrantes da Família");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 370, 130, 14);

        jLabel10.setText("Nome:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 180, 80, 14);

        nomePrincipal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nomePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(nomePrincipal);
        nomePrincipal.setBounds(190, 180, 260, 19);

        cpfPrincipal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(cpfPrincipal);
        cpfPrincipal.setBounds(190, 210, 150, 19);

        jLabel11.setText("CPF:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 210, 60, 14);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 570, 90, 23);

        jLabel12.setText("Doença:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 500, 50, 14);

        estado.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(estado);
        estado.setBounds(400, 320, 50, 19);

        doenca.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(doenca);
        doenca.setBounds(190, 500, 100, 19);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 570, 73, 23);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 540, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MembroFamilia novo = new MembroFamilia(nome.getText(), cpf.getText(), doenca.getText(),true);
        Familia nova = new Familia(cidade.getText(),estado.getText(),cep.getText(), novo);
        Lista.adiciona(nova);
        new TelaAgente().setVisible(true);
        this.dispose();
       
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new TelaAgente().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nomePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePrincipalActionPerformed
    private void add(Familia nova){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFamilia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField cpfPrincipal;
    private javax.swing.JTextField doenca;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomePrincipal;
    // End of variables declaration//GEN-END:variables
}
